In [1]:
# ==========================================
# Notebook 02 : Data Preprocessing
# ==========================================

import pandas as pd
import numpy as np

import os
import sys

# Add project root to Python path
sys.path.append(os.path.abspath(".."))

from src.utils import project_name

print(f"Project: {project_name()}")
print("Notebook 02 - Data Preprocessing")

Project: FairHire
Notebook 02 - Data Preprocessing

In [2]:
# Load datasets

job_df = pd.read_csv("../data/raw/job_description_dataset.csv")
resume_df = pd.read_csv("../data/raw/resume_dataset.csv")

print("Job Dataset Shape :", job_df.shape)
print("Resume Dataset Shape :", resume_df.shape)

Job Dataset Shape : (1068, 7)
Resume Dataset Shape : (10174, 5)

In [4]:
display(job_df.head())

display(resume_df.head())

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...

,Role,Resume,Decision,Reason_for_decision,Job_Description
0,E-commerce Specialist,Here's a professional resume for Jason Jones:\...,reject,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
1,Game Developer,Here's a professional resume for Ann Marshall:...,select,Strong technical skills in AI and ML.,Help us build the next-generation products as ...
2,Human Resources Specialist,Here's a professional resume for Patrick Mccla...,reject,Insufficient system design expertise for senio...,We need a Human Resources Specialist to enhanc...
3,E-commerce Specialist,Here's a professional resume for Patricia Gray...,select,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...
4,E-commerce Specialist,Here's a professional resume for Amanda Gross:...,reject,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...

In [5]:
# 4. Missing Values
print("Missing Values in Job Dataset")
display(job_df.isnull().sum())

print("\nMissing Values in Resume Dataset")
display(resume_df.isnull().sum())

Missing Values in Job Dataset

JobID                0
Title                1
ExperienceLevel      0
YearsOfExperience    0
Skills               0
Responsibilities     0
Keywords             0
dtype: int64

Missing Values in Resume Dataset

Role                   0
Resume                 0
Decision               0
Reason_for_decision    0
Job_Description        0
dtype: int64

In [7]:
# 5. Remove Missing Values
job_df = job_df.dropna()

resume_df = resume_df.dropna()

print("Job Dataset Shape :", job_df.shape)
print("Resume Dataset Shape :", resume_df.shape)

Job Dataset Shape : (1067, 7)
Resume Dataset Shape : (10174, 5)

In [8]:
# 6. Duplicate Analysis
print("Duplicate Job Records :", job_df.duplicated().sum())

print("Duplicate Resume Records :", resume_df.duplicated().sum())

Duplicate Job Records : 0
Duplicate Resume Records : 0

In [ ]:
# 7. Download NLTK Resources
import nltk

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

In [11]:
# 8 . Import Preprocessing Module
from src.preprocessing import clean_text

print("Preprocessing module imported successfully.")

Preprocessing module imported successfully.

In [12]:
# 9. Apply Preprocessing
resume_df["Clean_Resume"] = resume_df["Resume"].apply(clean_text)

resume_df["Clean_Job_Description"] = (
    resume_df["Job_Description"].apply(clean_text)
)

In [19]:
# 9.5 Clean Job Dataset

job_df["Clean_Skills"] = job_df["Skills"].apply(clean_text)

job_df["Clean_Responsibilities"] = job_df["Responsibilities"].apply(clean_text)

job_df["Clean_Keywords"] = job_df["Keywords"].apply(clean_text)

In [20]:
job_df["Clean_Job_Text"] = (
    job_df["Title"].fillna("") + " " +
    job_df["Clean_Skills"] + " " +
    job_df["Clean_Responsibilities"] + " " +
    job_df["Clean_Keywords"]
)

In [13]:
# 10. Display Original and Cleaned Resume
print("=" * 80)
print("ORIGINAL RESUME")
print("=" * 80)

print(resume_df.loc[0, "Resume"][:800])

print("\n")

print("=" * 80)
print("CLEANED RESUME")
print("=" * 80)

print(resume_df.loc[0, "Clean_Resume"][:800])

================================================================================
ORIGINAL RESUME
================================================================================
Here's a professional resume for Jason Jones:

Jason Jones
E-commerce Specialist

Contact Information:

* Email: [jasonjones@email.com](mailto:jasonjones@email.com)
* Phone: 555-123-4567
* LinkedIn: linkedin.com/in/jasonjones

Summary:
Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies.

Professional Experience:

E-commerce Specialist, XYZ Corporation (2018-Present)

* Managed inventory levels across multiple channels, resulting


================================================================================
CLEANED RESUME
================================================================================
here professional resume jason jones jason jones ecommerce specialist contact information email phone 5551234567 linkedin linkedincominjasonjones summary resultsdriven ecommerce specialist 5 year experience inventory management seo online advertising analytics proven track record increasing online sale improving website traffic optimizing inventory level skilled analyzing complex data set identifying trend making datadriven decision passionate staying uptodate latest ecommerce trend technology professional experience ecommerce specialist xyz corporation 2018present managed inventory level across multiple channel resulting 25 reduction stockouts 15 reduction overstocking developed implemented seo strategy increased website traffic 30 improved search engine ranking 20 created executed online

In [21]:
# Create processed directory
os.makedirs("../data/processed", exist_ok=True)

# Save cleaned datasets
resume_df.to_csv(
    "../data/processed/cleaned_resume_dataset.csv",
    index=False
)

job_df.to_csv(
    "../data/processed/cleaned_job_dataset.csv",
    index=False
)

print("✅ Cleaned resume dataset saved.")
print("✅ Cleaned job dataset saved.")

✅ Cleaned resume dataset saved.
✅ Cleaned job dataset saved.

In [25]:
print("Cleaned Resume Dataset")
display(resume_df.head())

print("\nCleaned Job Dataset")
display(job_df.head())

Cleaned Resume Dataset

,Role,Resume,Decision,Reason_for_decision,Job_Description,Clean_Resume,Clean_Job_Description
0,E-commerce Specialist,Here's a professional resume for Jason Jones:\...,reject,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...,here professional resume jason jones jason jon...,part passionate team forefront machine learnin...
1,Game Developer,Here's a professional resume for Ann Marshall:...,select,Strong technical skills in AI and ML.,Help us build the next-generation products as ...,here professional resume ann marshall ann mars...,help u build nextgeneration product game devel...
2,Human Resources Specialist,Here's a professional resume for Patrick Mccla...,reject,Insufficient system design expertise for senio...,We need a Human Resources Specialist to enhanc...,here professional resume patrick mcclain patri...,need human resource specialist enhance team te...
3,E-commerce Specialist,Here's a professional resume for Patricia Gray...,select,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...,here professional resume patricia gray patrici...,part passionate team forefront cloud computing...
4,E-commerce Specialist,Here's a professional resume for Amanda Gross:...,reject,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...,here professional resume amanda gross amanda g...,looking experienced ecommerce specialist join ...

Cleaned Job Dataset

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords,Clean_Skills,Clean_Responsibilities,Clean_Keywords,Clean_Job_Text
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,c vbnet basic net framework net core fundament...,assist coding debugging application learn appl...,net c aspnet mvc entity framework sql server l...,.NET Developer c vbnet basic net framework net...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,c net framework basic aspnet razor html cs jav...,write simple c program guidance support develo...,net c aspnet mvc entity framework sql server r...,.NET Developer c net framework basic aspnet ra...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...,c vbnet basic net core aspnet mvc html cs java...,contribute development small module assist bug...,net c aspnet mvc sql server entity framework git,.NET Developer c vbnet basic net core aspnet m...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET,c net framework aspnet basic sql server html c...,support software design documentation assist s...,net c sql server entity framework aspnet,.NET Developer c net framework aspnet basic sq...
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,c aspnet mvc entity framework basic sql server...,learn design build aspnet application assist c...,net c aspnet mvc entity framework sql server,.NET Developer c aspnet mvc entity framework b...

# **Summary**

## Objective
This notebook prepares the raw textual data for machine learning by cleaning and standardizing both resume and job description datasets.

## Tasks Completed

- Loaded raw datasets
- Removed missing values
- Verified duplicate records
- Built a reusable preprocessing module (`src/preprocessing.py`)
- Applied preprocessing to:
  - Resume text
  - Resume job descriptions
  - Job skills
  - Job responsibilities
  - Job keywords
- Created cleaned text columns
- Saved processed datasets to `data/processed/`

## Output Files

- cleaned_resume_dataset.csv
- cleaned_job_dataset.csv

These datasets will be used for feature engineering in Notebook 03.