In [1]:
# ==========================================
# Notebook 02 : Data Preprocessing
# ==========================================

import pandas as pd
import numpy as np

import os
import sys

# Add project root to Python path
sys.path.append(os.path.abspath(".."))

from src.utils import project_name

print(f"Project: {project_name()}")
print("Notebook 02 - Data Preprocessing")

Project: FairHire
Notebook 02 - Data Preprocessing

In [2]:
# Load datasets

job_df = pd.read_csv("../data/raw/job_description_dataset.csv")
resume_df = pd.read_csv("../data/processed/resume_dataset_v3.csv")

print("Job Dataset Shape :", job_df.shape)
print("Resume Dataset Shape :", resume_df.shape)

Job Dataset Shape : (1068, 7)
Resume Dataset Shape : (150000, 5)

In [3]:
display(job_df.head())

display(resume_df.head())

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...

,Role,Resume,Decision,Reason_for_decision,Job_Description
0,Operations Manager,Operations Manager with 7 years of experience ...,select,Resume matches the required skills and experie...,We are hiring a Operations Manager to support ...
1,Full Stack Engineer,Software Engineer with 5 years of experience i...,select,Resume matches the required skills and experie...,We are hiring a Full Stack Engineer to support...
2,Customer Support Specialist,Sales Representative with 2 years of experienc...,reject,Resume lacks important skills or experience.,We are hiring a Customer Support Specialist to...
3,Customer Support Specialist,FP&A Analyst with 3 years of experience in Cyb...,reject,Resume lacks important skills or experience.,We are hiring a Customer Support Specialist to...
4,Business Development Manager,Project Manager with 2 years of experience in ...,reject,Resume lacks important skills or experience.,We are hiring a Business Development Manager t...

In [4]:
# 4. Missing Values
print("Missing Values in Job Dataset")
display(job_df.isnull().sum())

print("\nMissing Values in Resume Dataset")
display(resume_df.isnull().sum())

Missing Values in Job Dataset

JobID                0
Title                1
ExperienceLevel      0
YearsOfExperience    0
Skills               0
Responsibilities     0
Keywords             0
dtype: int64

Missing Values in Resume Dataset

Role                   0
Resume                 0
Decision               0
Reason_for_decision    0
Job_Description        0
dtype: int64

In [5]:
# 5. Remove Missing Values
job_df = job_df.dropna()

resume_df = resume_df.dropna()

print("Job Dataset Shape :", job_df.shape)
print("Resume Dataset Shape :", resume_df.shape)

Job Dataset Shape : (1067, 7)
Resume Dataset Shape : (150000, 5)

In [6]:
# 6. Duplicate Analysis
print("Duplicate Job Records :", job_df.duplicated().sum())

print("Duplicate Resume Records :", resume_df.duplicated().sum())

Duplicate Job Records : 0
Duplicate Resume Records : 1

In [7]:
# 7. Download NLTK Resources
#import nltk

#nltk.download("stopwords")
#nltk.download("wordnet")
#nltk.download("omw-1.4")

In [8]:
# 8 . Import Preprocessing Module
from src.preprocessing import clean_text

print("Preprocessing module imported successfully.")

print("Preprocessing module imported successfully.")

Preprocessing module imported successfully.
Preprocessing module imported successfully.

In [9]:
# 9. Apply Preprocessing
resume_df["Clean_Resume"] = resume_df["Resume"].apply(clean_text)

resume_df["Clean_Job_Description"] = (
    resume_df["Job_Description"].apply(clean_text)
)

In [10]:
# 9.5 Clean Job Dataset

job_df["Clean_Skills"] = job_df["Skills"].apply(clean_text)

job_df["Clean_Responsibilities"] = job_df["Responsibilities"].apply(clean_text)

job_df["Clean_Keywords"] = job_df["Keywords"].apply(clean_text)

In [11]:
job_df["Clean_Job_Text"] = (
    job_df["Title"].fillna("") + " " +
    job_df["Clean_Skills"] + " " +
    job_df["Clean_Responsibilities"] + " " +
    job_df["Clean_Keywords"]
)

In [12]:
# 10. Display Original and Cleaned Resume
print("=" * 80)
print("ORIGINAL RESUME")
print("=" * 80)

print(resume_df.loc[0, "Resume"][:800])

print("\n")

print("=" * 80)
print("CLEANED RESUME")
print("=" * 80)

print(resume_df.loc[0, "Clean_Resume"][:800])

================================================================================
ORIGINAL RESUME
================================================================================
Operations Manager with 7 years of experience in FinTech. ['Asana' 'KPIs' 'Project Planning' 'Risk Management'
 'Stakeholder Communication' 'Jira' 'Process Improvement'
 'Timeline Management'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


================================================================================
CLEANED RESUME
================================================================================
operation manager 7 year experience fintech. asana kpis project planning risk management stakeholder communication jira process improvement timeline management delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance

In [13]:
# Create processed directory
os.makedirs("../data/processed", exist_ok=True)

# Save cleaned datasets
resume_df.to_csv(
    "../data/processed/cleaned_resume_dataset.csv",
    index=False
)

job_df.to_csv(
    "../data/processed/cleaned_job_dataset.csv",
    index=False
)

print("Cleaned resume dataset saved.")
print("Cleaned job dataset saved.")

Cleaned resume dataset saved.
Cleaned job dataset saved.

In [14]:
print("Cleaned Resume Dataset")
display(resume_df.head())

print("\nCleaned Job Dataset")
display(job_df.head())

Cleaned Resume Dataset

,Role,Resume,Decision,Reason_for_decision,Job_Description,Clean_Resume,Clean_Job_Description
0,Operations Manager,Operations Manager with 7 years of experience ...,select,Resume matches the required skills and experie...,We are hiring a Operations Manager to support ...,operation manager 7 year experience fintech. a...,hiring operation manager support team e commer...
1,Full Stack Engineer,Software Engineer with 5 years of experience i...,select,Resume matches the required skills and experie...,We are hiring a Full Stack Engineer to support...,software engineer 5 year experience gaming. ja...,hiring full stack engineer support team retail...
2,Customer Support Specialist,Sales Representative with 2 years of experienc...,reject,Resume lacks important skills or experience.,We are hiring a Customer Support Specialist to...,sale representative 2 year experience travel. ...,hiring customer support specialist support tea...
3,Customer Support Specialist,FP&A Analyst with 3 years of experience in Cyb...,reject,Resume lacks important skills or experience.,We are hiring a Customer Support Specialist to...,fp analyst 3 year experience cybersecurity. va...,hiring customer support specialist support tea...
4,Business Development Manager,Project Manager with 2 years of experience in ...,reject,Resume lacks important skills or experience.,We are hiring a Business Development Manager t...,project manager 2 year experience cybersecurit...,hiring business development manager support te...

Cleaned Job Dataset

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords,Clean_Skills,Clean_Responsibilities,Clean_Keywords,Clean_Job_Text
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,csharp vbdotnet basic dotnet framework dotnet ...,assist coding debugging application learn appl...,dotnet csharp aspdotnet mvc entity framework s...,.NET Developer csharp vbdotnet basic dotnet fr...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,csharp dotnet framework basic aspdotnet razor ...,write simple csharp program guidance support d...,dotnet csharp aspdotnet mvc entity framework s...,.NET Developer csharp dotnet framework basic a...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...,csharp vbdotnet basic dotnet core aspdotnet mv...,contribute development small module assist bug...,dotnet csharp aspdotnet mvc sql server entity ...,.NET Developer csharp vbdotnet basic dotnet co...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET,csharp dotnet framework aspdotnet basic sql se...,support software design documentation assist s...,dotnet csharp sql server entity framework aspd...,.NET Developer csharp dotnet framework aspdotn...
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,csharp aspdotnet mvc entity framework basic sq...,learn design build aspdotnet application assis...,dotnet csharp aspdotnet mvc entity framework s...,.NET Developer csharp aspdotnet mvc entity fra...

In [15]:
keywords = ["c++", "c#", ".net", "react.js", "node.js"]

for keyword in keywords:
    result = resume_df[
        resume_df["Resume"].str.contains(keyword, case=False, na=False, regex=False)
    ]

    print(f"{keyword}: {len(result)} resumes found")

c++: 0 resumes found
c#: 0 resumes found
.net: 0 resumes found
react.js: 0 resumes found
node.js: 0 resumes found

In [16]:
# Display original vs cleaned resumes

resume_df['Cleaned_Resume'] = resume_df['Resume'].apply(clean_text)
sample_df = resume_df[['Resume', 'Cleaned_Resume']].sample(10, random_state=42)

for idx, row in sample_df.iterrows():
    print("=" * 100)
    print("ORIGINAL RESUME:\n")
    print(row["Resume"][:800])  # First 800 characters
    print("\n")
    print("-" * 100)
    print("CLEANED RESUME:\n")
    print(row["Cleaned_Resume"][:800])
    print("\n")

====================================================================================================
ORIGINAL RESUME:

Backend Engineer with 9 years of experience in Healthcare. ['Databases' 'Python' 'Java' 'OOP' 'Git' 'Unit Testing'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

backend engineer 9 year experience healthcare. database python java oop git unit testing delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Marketing Manager with 6 years of experience in Healthcare. ['Google Ads' 'Meta Ads' 'Landing Pages' 'Email Marketing'
 'Conversion Optimization'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

marketing manager 6 year experience healthcare. google ad meta ad landing page email marketing conversion optimization delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Operations Manager with 2 years of experience in Retail. ['Process Improvement' 'Reporting' 'Stakeholder Communication'
 'Risk Management' 'KPIs' 'Jira' 'Cross-functional Coordination'
 'Timeline Management'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

operation manager 2 year experience retail. process improvement reporting stakeholder communication risk management kpis jira cross functional coordination timeline management delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Financial Analyst with 6 years of experience in Retail. ['Reporting' 'Financial Modeling' 'Excel' 'Variance Analysis' 'Accounting'
 'Valuation' 'Forecasting'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

financial analyst 6 year experience retail. reporting financial modeling excel variance analysis accounting valuation forecasting delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

BI Analyst with 6 years of experience in Travel. ['Power BI' 'Python' 'ETL' 'Excel' 'A/B Testing'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

bi analyst 6 year experience travel. power bi python etl excel b testing delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Operations Manager with 2 years of experience in EdTech. ['Risk Management' 'Stakeholder Communication' 'Jira'
 'Process Improvement' 'Cross-functional Coordination' 'KPIs'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

operation manager 2 year experience edtech. risk management stakeholder communication jira process improvement cross functional coordination kpis delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Account Executive with 12 years of experience in Cybersecurity. ['Negotiation' 'Discovery Calls' 'Lead Generation' 'Pipeline Management'
 'Closing' 'Account Management'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

account executive 12 year experience cybersecurity. negotiation discovery call lead generation pipeline management closing account management delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Account Executive with 2 years of experience in Logistics. ['Discovery Calls' 'Prospecting' 'CRM' 'Pipeline Management'
 'Outbound Outreach' 'Account Management'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

account executive 2 year experience logistics. discovery call prospecting crm pipeline management outbound outreach account management delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Performance Marketer with 2 years of experience in E-commerce. ['A/B Testing' 'Landing Pages' 'Email Marketing' 'Google Ads' 'SEO'
 'Content Marketing' 'Copywriting' 'Conversion Optimization'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

performance marketer 2 year experience e commerce. b testing landing page email marketing google ad seo content marketing copywriting conversion optimization delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance


====================================================================================================
ORIGINAL RESUME:

Data Analyst with 12 years of experience in Logistics. ['ETL' 'Python' 'Pandas' 'Statistics' 'A/B Testing' 'Excel' 'Power BI'
 'Data Visualization'] ['Delivered results using structured workflows and clear communication'
 'Collaborated with stakeholders to define needs and execute tasks'
 'Maintained reporting and documentation to support team performance']


----------------------------------------------------------------------------------------------------
CLEANED RESUME:

data analyst 12 year experience logistics. etl python panda statistic b testing excel power bi data visualization delivered result using structured workflow clear communication collaborated stakeholder define need execute task maintained reporting documentation support team performance