In [1]:
import os
import joblib
import warnings

import numpy as np
import pandas as pd

from scipy.sparse import csr_matrix
from scipy.sparse import hstack

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)

warnings.filterwarnings("ignore")

In [2]:
resume_df = pd.read_pickle("../outputs/resume_df.pkl")

print("=" * 50)
print("Dataset Loaded Successfully")
print("=" * 50)

print("Shape :", resume_df.shape)
print()

display(resume_df.head())

==================================================
Dataset Loaded Successfully
==================================================
Shape : (150000, 10)

,Role,Resume,Decision,Reason_for_decision,Job_Description,Clean_Resume,Clean_Job_Description,Combined_Text,Keyword_Coverage,Semantic_Similarity
0,Operations Manager,Operations Manager with 7 years of experience ...,select,Resume matches the required skills and experie...,We are hiring a Operations Manager to support ...,operation manager 7 year experience fintech. a...,hiring operation manager support team e commer...,operation manager 7 year experience fintech. a...,46.43,0.695716
1,Full Stack Engineer,Software Engineer with 5 years of experience i...,select,Resume matches the required skills and experie...,We are hiring a Full Stack Engineer to support...,software engineer 5 year experience gaming. ja...,hiring full stack engineer support team retail...,software engineer 5 year experience gaming. ja...,29.63,0.629071
2,Customer Support Specialist,Sales Representative with 2 years of experienc...,reject,Resume lacks important skills or experience.,We are hiring a Customer Support Specialist to...,sale representative 2 year experience travel. ...,hiring customer support specialist support tea...,sale representative 2 year experience travel. ...,19.23,0.502708
3,Customer Support Specialist,FP&A Analyst with 3 years of experience in Cyb...,reject,Resume lacks important skills or experience.,We are hiring a Customer Support Specialist to...,fp analyst 3 year experience cybersecurity. va...,hiring customer support specialist support tea...,fp analyst 3 year experience cybersecurity. va...,22.22,0.428280
4,Business Development Manager,Project Manager with 2 years of experience in ...,reject,Resume lacks important skills or experience.,We are hiring a Business Development Manager t...,project manager 2 year experience cybersecurit...,hiring business development manager support te...,project manager 2 year experience cybersecurit...,27.59,0.423714

In [3]:
tfidf = joblib.load("../models/tfidf_vectorizer.pkl")

print("TF-IDF Vectorizer Loaded Successfully")

TF-IDF Vectorizer Loaded Successfully

In [4]:
X_text = tfidf.transform(resume_df["Combined_Text"])

print("TF-IDF Shape:", X_text.shape)

TF-IDF Shape: (150000, 156)

In [5]:
numeric_features = resume_df[
    [
        "Keyword_Coverage",
        "Semantic_Similarity",
    ]
].values

print(numeric_features.shape)

(150000, 2)

In [6]:
X = hstack([X_text, numeric_features])

print("Final Feature Matrix Shape:", X.shape)

Final Feature Matrix Shape: (150000, 158)

In [7]:
y = resume_df["Decision"].map(
    {
        "reject": 0,
        "select": 1,
    }
)

print(y.value_counts())

Decision
1    75000
0    75000
Name: count, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y,
)

print("Training :", X_train.shape)
print("Testing  :", X_test.shape)

Training : (120000, 158)
Testing  : (30000, 158)

In [9]:
joblib.dump(
    tfidf,
    "../models/vectorizer.pkl"
)

['../models/vectorizer.pkl']

In [10]:
import os

os.makedirs("../models", exist_ok=True)

X_train = joblib.load("../models/X_train_scaled.pkl")
X_test = joblib.load("../models/X_test_scaled.pkl")

joblib.dump(y_train, "../models/y_train.pkl")
joblib.dump(y_test, "../models/y_test.pkl")

print("Train/Test data saved successfully.")

Train/Test data saved successfully.

## Train Model

In [11]:
import joblib

# Load train-test splits
X_train = joblib.load("../models/X_train_scaled.pkl")
X_test = joblib.load("../models/X_test_scaled.pkl")

y_train = joblib.load("../models/y_train.pkl")
y_test = joblib.load("../models/y_test.pkl")

print("Training:", X_train.shape)
print("Testing :", X_test.shape)

Training: (120000, 156)
Testing : (30000, 156)

In [12]:
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack

# Last two columns are numerical features
X_train_tfidf = X_train.tocsr()[:, :-2]
X_test_tfidf = X_test.tocsr()[:, :-2]

X_train_numeric = X_train.tocsr()[:, -2:].toarray()
X_test_numeric = X_test.tocsr()[:, -2:].toarray()

scaler = StandardScaler()

X_train_numeric_scaled = scaler.fit_transform(X_train_numeric)
X_test_numeric_scaled = scaler.transform(X_test_numeric)

X_train_scaled = hstack([X_train_tfidf, X_train_numeric_scaled])
X_test_scaled = hstack([X_test_tfidf, X_test_numeric_scaled])

print("Scaled feature matrix:")
print(X_train_scaled.shape)
print(X_test_scaled.shape)

Scaled feature matrix:
(120000, 156)
(30000, 156)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

import pandas as pd
import time

In [14]:
start = time.time()

logistic_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

logistic_model.fit(X_train_scaled, y_train)

pred = logistic_model.predict(X_test_scaled)

logistic_accuracy = accuracy_score(y_test, pred)

print("Logistic Regression Accuracy:", logistic_accuracy)

print("Training Time:", round(time.time() - start, 2), "seconds")

Logistic Regression Accuracy: 0.9322
Training Time: 1.4 seconds

In [15]:
start = time.time()

svm_model = LinearSVC(
    random_state=42
)

svm_model.fit(X_train_scaled, y_train)

pred = svm_model.predict(X_test_scaled)

svm_accuracy = accuracy_score(y_test, pred)

print("Linear SVM Accuracy:", svm_accuracy)

print("Training Time:", round(time.time() - start, 2), "seconds")

Linear SVM Accuracy: 0.9363
Training Time: 3.33 seconds

In [16]:
start = time.time()

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_scaled, y_train)

pred = rf_model.predict(X_test_scaled)

rf_accuracy = accuracy_score(y_test, pred)

print("Random Forest Accuracy:", rf_accuracy)

print("Training Time:", round(time.time() - start, 2), "seconds")

Random Forest Accuracy: 0.9368333333333333
Training Time: 148.66 seconds

In [17]:
import xgboost

print(xgboost.__version__)

3.3.0

In [18]:
from xgboost import XGBClassifier

start = time.time()

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric="logloss",
    n_jobs=-1
)

xgb_model.fit(X_train_scaled, y_train)

pred = xgb_model.predict(X_test_scaled)

xgb_accuracy = accuracy_score(y_test, pred)

print("XGBoost Accuracy:", xgb_accuracy)

print("Training Time:", round(time.time() - start, 2), "seconds")

XGBoost Accuracy: 0.9413333333333334
Training Time: 4.76 seconds

In [19]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Linear SVM",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        logistic_accuracy,
        svm_accuracy,
        rf_accuracy,
        xgb_accuracy
    ]
})

results = results.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

results

                 Model  Accuracy
0              XGBoost  0.941333
1        Random Forest  0.936833
2           Linear SVM  0.936300
3  Logistic Regression  0.932200

In [20]:
import os
import joblib

os.makedirs("../models/trained_models", exist_ok=True)

joblib.dump(logistic_model, "../models/trained_models/logistic_regression.pkl")
joblib.dump(svm_model, "../models/trained_models/linear_svm.pkl")
joblib.dump(rf_model, "../models/trained_models/random_forest.pkl")
joblib.dump(xgb_model, "../models/trained_models/xgboost.pkl")

print("All trained models saved successfully!")

All trained models saved successfully!

In [21]:
model_dict = {
    "Logistic Regression": logistic_model,
    "Linear SVM": svm_model,
    "Random Forest": rf_model,
    "XGBoost": xgb_model,
}

accuracy_dict = {
    "Logistic Regression": logistic_accuracy,
    "Linear SVM": svm_accuracy,
    "Random Forest": rf_accuracy,
    "XGBoost": xgb_accuracy,
}

best_model_name = max(accuracy_dict, key=accuracy_dict.get)
best_model = model_dict[best_model_name]

print("=" * 50)
print("Best Model :", best_model_name)
print("Accuracy   :", round(accuracy_dict[best_model_name], 4))
print("=" * 50)

==================================================
Best Model : XGBoost
Accuracy   : 0.9413
==================================================

In [22]:
joblib.dump(best_model, "../models/fairhire_model.pkl")

print("Best model saved successfully!")

Best model saved successfully!

In [23]:
os.makedirs("../results", exist_ok=True)

results.to_csv("../results/model_comparison.csv", index=False)

print("Model comparison saved successfully!")

Model comparison saved successfully!

In [24]:
print("=" * 60)
print("Training Pipeline Completed Successfully!")
print("=" * 60)

print("\nSaved Models:")
print(os.listdir("../models"))

print("\nTrained Models:")
print(os.listdir("../models/trained_models"))

print("\nResults:")
print(os.listdir("../results"))

============================================================
Training Pipeline Completed Successfully!
============================================================

Saved Models:
['best_model.pkl', 'fairhire_model.pkl', 'feature_names.pkl', 'job_embeddings.pkl', 'project_summary.pkl', 'resume_embeddings.pkl', 'scaler.pkl', 'skill_dictionary.pkl', 'tfidf_vectorizer.pkl', 'top_features.pkl', 'trained_models', 'vectorizer.pkl', 'X_test_scaled.pkl', 'X_train_scaled.pkl', 'y_test.pkl', 'y_train.pkl']

Trained Models:
['dummy_classifier.pkl', 'linear_svm.pkl', 'logistic_regression.pkl', 'multinomial_naive_bayes.pkl', 'random_forest.pkl', 'xgboost.pkl']

Results:
['fairhire_predictions.csv', 'feature_importance.csv', 'model_comparison.csv', 'model_evaluation_results.csv', 'model_metrics.csv', 'prediction_results.csv', 'shap_summary.png', 'shap_summary_plot.png']

In [25]:
import csv
import joblib
import os

os.makedirs("../models", exist_ok=True)

results_path = "../results/model_comparison.csv"
model_paths = {
    "Logistic Regression": "../models/trained_models/logistic_regression.pkl",
    "Linear SVM": "../models/trained_models/linear_svm.pkl",
    "Random Forest": "../models/trained_models/random_forest.pkl",
    "XGBoost": "../models/trained_models/xgboost.pkl",
}

if os.path.exists(results_path):
    with open(results_path, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    best_row = max(rows, key=lambda r: float(r["Accuracy"]))
    best_name = best_row["Model"]
    best_model = joblib.load(model_paths[best_name])
    accuracy = float(best_row["Accuracy"])
else:
    raise FileNotFoundError(
        "model_comparison.csv not found. Run the training cells first."
    )

joblib.dump(best_model, "../models/best_model.pkl")

print("=" * 50)
print("Best Model Saved Successfully")
print(f"Best Model : {best_name}")
print(f"Accuracy   : {accuracy:.4f}")
print("=" * 50)

==================================================
Best Model Saved Successfully
Best Model : XGBoost
Accuracy   : 0.9413
==================================================

In [26]:
os.makedirs("../models", exist_ok=True)

model_sources = {
	"../models/logistic_regression.pkl": "../models/trained_models/logistic_regression.pkl",
	"../models/linear_svm.pkl": "../models/trained_models/linear_svm.pkl",
	"../models/random_forest.pkl": "../models/trained_models/random_forest.pkl",
	"../models/xgboost.pkl": "../models/trained_models/xgboost.pkl",
}

for target_path, source_path in model_sources.items():
	model = joblib.load(source_path)
	joblib.dump(model, target_path)

In [27]:
import os
import joblib

from scipy.sparse import hstack
from sklearn.preprocessing import StandardScaler

os.makedirs("../models", exist_ok=True)

if "X_train_scaled" not in globals():
	X_train_tfidf = X_train[:, :-2]
	X_test_tfidf = X_test[:, :-2]

	X_train_numeric = X_train[:, -2:].toarray()
	X_test_numeric = X_test[:, -2:].toarray()

	if "scaler" not in globals():
		scaler = StandardScaler()
		X_train_numeric_scaled = scaler.fit_transform(X_train_numeric)
	else:
		X_train_numeric_scaled = scaler.transform(X_train_numeric)

	X_test_numeric_scaled = scaler.transform(X_test_numeric)

	X_train_scaled = hstack([X_train_tfidf, X_train_numeric_scaled])
	X_test_scaled = hstack([X_test_tfidf, X_test_numeric_scaled])

joblib.dump(X_test_scaled, "../models/X_test_scaled.pkl")
joblib.dump(X_train_scaled, "../models/X_train_scaled.pkl")
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']